/*
 * This source file was generated by the Gradle 'init' task
 */


package ie.tudublin

import java.io.File
import java.io.IOException


class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)

    print("Enter text file name: ")
    val filePath = readln() // Reads a line from standard input as String
    var content: String
    val basePath = "C:\\Users\\C23398751\\Downloads\\sudoku\\"
    val file = File(basePath + filePath)

    if (!file.exists()) {
        println("Error: File '$filePath' not found.")
        return
    }
    
    try {
    

        content = file.readText(Charsets.UTF_8)

        } catch (e: IOException) {
        println("Error reading file: ${e.message}")
        return
    }

    val rows = content.lines().filter { it.isNotBlank() }

    Sudoku(rows).solve()
}
